[theme]
base = "light"
primaryColor = "#007BFF"       # Blue
backgroundColor = "#FFFFFF"    # White
secondaryBackgroundColor = "#E9F2FF"
textColor = "#000000"
font = "sans serif"


[server]
headless = true
port = 8501
enableCORS = false
